"""Export module — Markdown to PDF conversion using fpdf2."""

from __future__ import annotations

import logging
import re

import markdown
from fpdf import FPDF

logger = logging.getLogger(__name__)


# --- Markdown → HTML (for preview) ---

REPORT_CSS = """
body {
    font-family: 'Inter', 'Segoe UI', sans-serif;
    color: #1a1a2e;
    line-height: 1.7;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
    font-size: 14px;
}
h1 { color: #0f0f23; font-size: 28px; border-bottom: 3px solid #6366f1; padding-bottom: 12px; }
h2 { color: #16213e; font-size: 22px; border-bottom: 1px solid #e0e0e0; padding-bottom: 8px; }
h3 { color: #1a1a2e; font-size: 18px; }
a { color: #6366f1; text-decoration: none; }
blockquote { border-left: 4px solid #6366f1; background: #f8f9ff; padding: 12px 20px; margin: 16px 0; }
code { background: #f0f0f5; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #ddd; padding: 10px 14px; text-align: left; }
th { background: #6366f1; color: white; font-weight: 600; }
"""


def markdown_to_html(md_content: str) -> str:
    """Convert Markdown to styled HTML."""
    html_body = markdown.markdown(
        md_content,
        extensions=["tables", "fenced_code", "toc", "nl2br"],
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Research Report</title>
    <style>{REPORT_CSS}</style>
</head>
<body>
{html_body}
<div style="margin-top:48px;border-top:1px solid #e0e0e0;padding-top:16px;color:#666;font-size:12px;text-align:center;">
    Generated by Multi-Agent Research Assistant
</div>
</body>
</html>"""


# --- Markdown → PDF (fpdf2) ---


# Common Unicode to ASCII replacements for latin-1 safe PDF output
_UNICODE_REPLACEMENTS = {
    "\u2022": "-",
    "\u2013": "-",
    "\u2014": "--",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2026": "...",
    "\u2192": "->",
    "\u2190": "<-",
    "\u2713": "[x]",
    "\u2714": "[x]",
    "\u2715": "[!]",
    "\u2716": "[!]",
    "\u2717": "[!]",
    "\u26a0": "[!]",
    "\u2705": "[x]",
    "\u274c": "[!]",
}


def _sanitize_latin1(text: str) -> str:
    """Replace common Unicode characters with ASCII equivalents for latin-1 PDF output."""
    for uc, repl in _UNICODE_REPLACEMENTS.items():
        text = text.replace(uc, repl)
    # Drop anything still outside latin-1
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _prepare_md(text: str) -> str:
    """Convert double-bracket links to nested bracket links and sanitize characters for latin-1 PDF output."""
    # Convert [[3]](url) to [[3](url)] so fpdf2 renders [3] as a clickable link
    text = re.sub(r"\[\[([^\]]+)\]\]\(([^\)]+)\)", r"[[\1](\2)]", text)
    return _sanitize_latin1(text)


class ReportPDF(FPDF):
    """Custom PDF class for research reports."""

    def header(self):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Multi-Agent Research Assistant", align="R", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def export_pdf(md_content: str) -> bytes:
    """Convert a Markdown report to PDF bytes using fpdf2.

    Args:
        md_content: The Markdown content to convert.

    Returns:
        PDF file as bytes.
    """
    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # Configure custom markdown link styling
    pdf.MARKDOWN_LINK_COLOR = (99, 102, 241)  # Indigo/Blue #6366f1
    pdf.MARKDOWN_LINK_UNDERLINE = True

    pdf.add_page()

    # Process markdown line by line
    lines = md_content.split("\n")

    for line in lines:
        stripped = line.strip()

        if not stripped:
            pdf.ln(4)
            continue

        # Headings
        elif stripped.startswith("#"):
            # Count the number of hashes
            hash_count = 0
            for char in stripped:
                if char == "#":
                    hash_count += 1
                else:
                    break
            
            # Check if there is a space after the hashes
            if stripped[hash_count:].startswith(" "):
                heading_text = stripped[hash_count:].strip()
                
                # Dynamic font sizing based on heading level
                if hash_count == 1:
                    pdf.set_font("Helvetica", "B", 20)
                    pdf.set_text_color(15, 15, 35)
                    pdf.multi_cell(0, 10, _prepare_md(heading_text), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")
                    # Underline H1
                    pdf.set_draw_color(99, 102, 241)
                    pdf.set_line_width(0.8)
                    y = pdf.get_y()
                    pdf.line(10, y, 200, y)
                    pdf.ln(6)
                elif hash_count == 2:
                    pdf.ln(4)
                    pdf.set_font("Helvetica", "B", 16)
                    pdf.set_text_color(22, 33, 62)
                    pdf.multi_cell(0, 9, _prepare_md(heading_text), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")
                    # Underline H2
                    pdf.set_draw_color(200, 200, 200)
                    pdf.set_line_width(0.3)
                    y = pdf.get_y()
                    pdf.line(10, y, 200, y)
                    pdf.ln(4)
                elif hash_count == 3:
                    pdf.ln(3)
                    pdf.set_font("Helvetica", "B", 13)
                    pdf.set_text_color(26, 26, 46)
                    pdf.multi_cell(0, 8, _prepare_md(heading_text), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")
                    pdf.ln(2)
                else:
                    # H4, H5, H6, etc.
                    pdf.ln(2)
                    pdf.set_font("Helvetica", "B", 11)
                    pdf.set_text_color(40, 40, 40)
                    pdf.multi_cell(0, 7, _prepare_md(heading_text), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")
                    pdf.ln(1)
            else:
                # If there's no space, treat it as a regular paragraph (e.g. "#word")
                pdf.set_font("Helvetica", "", 11)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 7, _prepare_md(stripped), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")

        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(40, 40, 40)
            bullet_text = _prepare_md(stripped[2:])
            pdf.cell(8, 7, "-")  # bullet character (latin-1 safe)
            rem_w = pdf.epw - (pdf.get_x() - pdf.l_margin)
            pdf.multi_cell(rem_w, 7, bullet_text, align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")

        elif stripped.startswith("---"):
            pdf.ln(4)
            pdf.set_draw_color(200, 200, 200)
            pdf.set_line_width(0.2)
            y = pdf.get_y()
            pdf.line(10, y, 200, y)
            pdf.ln(4)

        elif stripped.startswith(">"):
            # Blockquote
            pdf.set_font("Helvetica", "I", 11)
            pdf.set_text_color(80, 80, 80)
            quote_text = _prepare_md(stripped.lstrip("> "))
            x = pdf.get_x()
            y_start = pdf.get_y()
            pdf.set_x(x + 6)
            rem_w = pdf.epw - (pdf.get_x() - pdf.l_margin)
            pdf.multi_cell(rem_w, 7, quote_text, align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")
            y_end = pdf.get_y()
            # Draw dynamic left vertical border
            pdf.set_draw_color(99, 102, 241)
            pdf.set_line_width(0.8)
            pdf.line(x, y_start, x, y_end)
            pdf.ln(2)

        else:
            # Regular paragraph
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 7, _prepare_md(stripped), align="L", markdown=True, new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
